name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Make binaries
        uses: sosedoff/actions/golang-build@master
        # Uncomment to following piece to restrict targets
        # with:
        #   args: linux/amd64 darwin/amd64
